class Commands:
    LEECH = "leech@flixtortoolkitbot"
    PURGE = "purge@flixtortoolkitbot"
    PAUSEALL = "pauseall@flixtortoolkitbot"
    RESUMEALL = "resumeall@flixtortoolkitbot"
    STATUS = "status@flixtortoolkitbot"
    SETTINGS = "settings@flixtortoolkitbot"
    EXEC = "exec@flixtortoolkitbot"
    UPLOAD = "upload@flixtortoolkitbot"
    YTDL = "ytdl@flixtortoolkitbot"
    PYTDL = "pytdl@flixtortoolkitbot"
    ABOUT = "about@flixtortoolkitbot"
    GETLOGS = "getlogs@flixtortoolkitbot"
    SERVER = "server@flixtortoolkitbot"
    USERSETTINGS = "usetting@flixtortoolkitbot"
    INSTADL = "instadl@flixtortoolkitbot"
